# Site Settings
title: Sitio Web Adrian
email: adrian.rod.v@gmail.com
description: >
  Blog de proyectos personales.
baseurl: ""
github_username:  adrian-rdz
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
